In [2]:
import time

print(time.time())
print(time.ctime(360))
print(time.gmtime(360))
print(time.localtime(360))

# 현재 기준
print(time.gmtime())
t = time.gmtime()
# 특정 문자열로 전환
print(time.asctime(t))
# epoch 기준으로 전환
print(time.mktime(t))


1483314574.6260648
Thu Jan  1 09:06:00 1970
time.struct_time(tm_year=1970, tm_mon=1, tm_mday=1, tm_hour=0, tm_min=6, tm_sec=0, tm_wday=3, tm_yday=1, tm_isdst=0)
time.struct_time(tm_year=1970, tm_mon=1, tm_mday=1, tm_hour=9, tm_min=6, tm_sec=0, tm_wday=3, tm_yday=1, tm_isdst=0)
time.struct_time(tm_year=2017, tm_mon=1, tm_mday=1, tm_hour=23, tm_min=49, tm_sec=34, tm_wday=6, tm_yday=1, tm_isdst=0)
Sun Jan  1 23:49:34 2017
1483282174.0


In [39]:
import time
# 현재 기준

t = time.gmtime()
print(t)
# 특정 문자열로 전환
print(time.asctime(t))
# epoch 기준으로 전환
print(time.mktime(t))

time.struct_time(tm_year=2017, tm_mon=1, tm_mday=2, tm_hour=0, tm_min=53, tm_sec=9, tm_wday=0, tm_yday=2, tm_isdst=0)
Mon Jan  2 00:53:09 2017
1483285989.0


In [82]:
import calendar
    
#print(calendar.calendar(2017))
print(calendar.prmonth(2017, 1))
# 월요일은 0
print(calendar.weekday(2017, 1, 2))
# 2017년 1월의 1일은 일요일이고, 이 달은 31일까지
print(calendar.monthrange(2017,1))

    January 2017
Mo Tu We Th Fr Sa Su
                   1
 2  3  4  5  6  7  8
 9 10 11 12 13 14 15
16 17 18 19 20 21 22
23 24 25 26 27 28 29
30 31
 None
0
(6, 31)


In [61]:
import time

print(time.timezone)
print(time.tzname[0].encode("utf-16"))
print(str(time.tzname[0]).encode("utf-16").decode("utf-16"))
print(str(time.tzname[1]))
'''
 'altzone',

 'clock',
,
 'daylight',
 'get_clock_info',

 'monotonic',
 'perf_counter',
 'process_time',


 'struct_time',
,
 'timezone',
 'tzname'
 '''

-32400
b'\xff\xfe\xb4\x00\xeb\x00\xc7\x00\xd1\x00\xb9\x00\xce\x00\xb1\x00\xb9\x00 \x00\xc7\x00\xa5\x00\xc1\x00\xd8\x00\xbd\x00\xc3\x00'
´ëÇѹα¹ Ç¥ÁؽÃ
´ëÇѹα¹ Àϱ¤ Àý¾à ½Ã°£


"\n 'altzone',\n\n 'clock',\n,\n 'daylight',\n 'get_clock_info',\n\n 'monotonic',\n 'perf_counter',\n 'process_time',\n\n\n 'struct_time',\n,\n 'timezone',\n 'tzname'\n "

In [71]:
from pytz import all_timezones

print(len(all_timezones))
for zone in all_timezones:
    if 'Asia/Seoul' in zone:
        print( zone)

588
Asia/Seoul


In [45]:
import time
loc = time.localtime()
print(loc.tm_year)
print(loc.tm_mon)
print(loc.tm_mday)
print(loc.tm_wday)
print(loc.tm_yday)
print(loc.tm_hour)
print(loc.tm_min)
print(loc.tm_sec)

print(loc.tm_isdst)

2017
1
2
0
2
10
3
34
0


In [38]:
import time
# 현재 기준
l = time.localtime()

print(l)
# 1970년 기준
l1 = time.localtime(360)
print(l1)

time.struct_time(tm_year=2017, tm_mon=1, tm_mday=2, tm_hour=9, tm_min=50, tm_sec=25, tm_wday=0, tm_yday=2, tm_isdst=0)
time.struct_time(tm_year=1970, tm_mon=1, tm_mday=1, tm_hour=9, tm_min=6, tm_sec=0, tm_wday=3, tm_yday=1, tm_isdst=0)


In [36]:
# 현재 기준
import time
l = time.localtime()

t = time.gmtime()
print(l)
# 특정 문자열로 전환
print(time.asctime(t))
# epoch 기준으로 전환
print(time.mktime(t))

time.struct_time(tm_year=2017, tm_mon=1, tm_mday=2, tm_hour=9, tm_min=48, tm_sec=12, tm_wday=0, tm_yday=2, tm_isdst=0)
Mon Jan  2 00:48:12 2017
1483285692.0


In [6]:
import time

now = time.time()

print(now, "seconds since", time.gmtime(0)[:6])
print("")
print("or in other words:")
print ("- local time:", time.localtime(now))
print("- utc:", time.gmtime(now))

1483314932.8343544 seconds since (1970, 1, 1, 0, 0, 0)

or in other words:
- local time: time.struct_time(tm_year=2017, tm_mon=1, tm_mday=2, tm_hour=8, tm_min=55, tm_sec=32, tm_wday=0, tm_yday=2, tm_isdst=0)
- utc: time.struct_time(tm_year=2017, tm_mon=1, tm_mday=1, tm_hour=23, tm_min=55, tm_sec=32, tm_wday=6, tm_yday=1, tm_isdst=0)


In [10]:
import time

now = time.localtime(time.time())

print(time.asctime(now))
print(time.strftime("%y/%m/%d %H:%M", now))
print(time.strftime("%a %b %d", now))
print(time.strftime("%c", now))
print(time.strftime("%I %p", now))


Mon Jan  2 08:58:23 2017
17/01/02 08:58
Mon Jan 02
Mon Jan  2 08:58:23 2017
08 AM


In [23]:
import time

print(time.strptime("31 12 2000", "%d %m %Y"))

print(time.strptime("30 Nov 2000", "%d %b %Y"))

print(time.strptime("1 Jan 70 1:30pm", "%d %b %y %I:%M%p"))


time.struct_time(tm_year=2000, tm_mon=12, tm_mday=31, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=6, tm_yday=366, tm_isdst=-1)
time.struct_time(tm_year=2000, tm_mon=11, tm_mday=30, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=3, tm_yday=335, tm_isdst=-1)
time.struct_time(tm_year=1970, tm_mon=1, tm_mday=1, tm_hour=13, tm_min=30, tm_sec=0, tm_wday=3, tm_yday=1, tm_isdst=-1)


In [16]:
help(time.strptime)

Help on built-in function strptime in module time:

strptime(...)
    strptime(string, format) -> struct_time
    
    Parse a string to a time tuple according to a format specification.
    See the library reference manual for formatting codes (same as
    strftime()).
    
    Commonly used format codes:
    
    %Y  Year with century as a decimal number.
    %m  Month as a decimal number [01,12].
    %d  Day of the month as a decimal number [01,31].
    %H  Hour (24-hour clock) as a decimal number [00,23].
    %M  Minute as a decimal number [00,59].
    %S  Second as a decimal number [00,61].
    %z  Time zone offset from UTC.
    %a  Locale's abbreviated weekday name.
    %A  Locale's full weekday name.
    %b  Locale's abbreviated month name.
    %B  Locale's full month name.
    %c  Locale's appropriate date and time representation.
    %I  Hour (12-hour clock) as a decimal number [01,12].
    %p  Locale's equivalent of either AM or PM.
    
    Other codes may be available on yo

In [29]:
import time

t0 = time.time()
print(t0)
#local time
tm = time.localtime(t0)

print(tm)
print(time.mktime(tm))

print(tm)
print(time.gmtime(t0))

1483316375.2687688
time.struct_time(tm_year=2017, tm_mon=1, tm_mday=2, tm_hour=9, tm_min=19, tm_sec=35, tm_wday=0, tm_yday=2, tm_isdst=0)
1483316375.0
time.struct_time(tm_year=2017, tm_mon=1, tm_mday=2, tm_hour=9, tm_min=19, tm_sec=35, tm_wday=0, tm_yday=2, tm_isdst=0)
time.struct_time(tm_year=2017, tm_mon=1, tm_mday=2, tm_hour=0, tm_min=19, tm_sec=35, tm_wday=0, tm_yday=2, tm_isdst=0)


In [26]:
help(time.gmtime)

Help on built-in function gmtime in module time:

gmtime(...)
    gmtime([seconds]) -> (tm_year, tm_mon, tm_mday, tm_hour, tm_min,
                           tm_sec, tm_wday, tm_yday, tm_isdst)
    
    Convert seconds since the Epoch to a time tuple expressing UTC (a.k.a.
    GMT).  When 'seconds' is not passed in, convert the current time instead.
    
    If the platform supports the tm_gmtoff and tm_zone, they are available as
    attributes only.



In [35]:
import time

t= time.time()
print(time.ctime(t))

l= time.localtime()
print(time.asctime(l))

Mon Jan  2 09:28:42 2017
Mon Jan  2 09:28:42 2017


In [83]:
import pytz
import datetime

#타임존을 가져오기
for tzs in pytz.all_timezones :
    if 'Asia/Seoul' in tzs :
        tzs_seoul = tzs
    if 'America/New_York' in tzs :
        tzs_newyork = tzs

#뉴욕 타임 가져오기
print(' tzs new york ' )  
EST = pytz.timezone(tzs_newyork)
print(" ETS  type ", type(EST))
dt1 = datetime.datetime.now(tz=EST)
print(' tzs newyork', dt1)

#서울 타임가져오기
EST2 = pytz.timezone(tzs_seoul)
print(" ETS 2 type ", type(EST2))
dt2 = datetime.datetime.now(tz=EST2)
print(" seoul date time ", dt2)


 tzs new york 
 ETS  type  <class 'pytz.tzfile.America/New_York'>
 tzs newyork 2017-01-01 20:46:28.299948-05:00
 ETS 2 type  <class 'pytz.tzfile.Asia/Seoul'>
 seoul date time  2017-01-02 10:46:28.300948+09:00


In [87]:
import pytz

for tzs in pytz.all_timezones :
    if 'Asia/Seoul' in tzs :
        tzs_seoul = tzs
        break
        
a = pytz.timezone(tzs_seoul)
print(type(a))

<class 'pytz.tzfile.Asia/Seoul'>


In [98]:
import pytz

print(pytz.country_timezones('KR'))
print(pytz.country_names['kr'])
print(pytz.country_timezones('US'))
print(pytz.country_names['US'])

['Asia/Seoul']
Korea (South)
['America/New_York', 'America/Detroit', 'America/Kentucky/Louisville', 'America/Kentucky/Monticello', 'America/Indiana/Indianapolis', 'America/Indiana/Vincennes', 'America/Indiana/Winamac', 'America/Indiana/Marengo', 'America/Indiana/Petersburg', 'America/Indiana/Vevay', 'America/Chicago', 'America/Indiana/Tell_City', 'America/Indiana/Knox', 'America/Menominee', 'America/North_Dakota/Center', 'America/North_Dakota/New_Salem', 'America/North_Dakota/Beulah', 'America/Denver', 'America/Boise', 'America/Phoenix', 'America/Los_Angeles', 'America/Anchorage', 'America/Juneau', 'America/Sitka', 'America/Metlakatla', 'America/Yakutat', 'America/Nome', 'America/Adak', 'Pacific/Honolulu']
United States


In [100]:
import pytz
a = pytz.utc
print(type(a))

<class 'pytz.UTC'>


In [104]:
import pytz
from datetime import datetime

tz = pytz.timezone('Asia/Seoul')
print(datetime(2017, 1, 2, tzinfo=tz))

print(datetime(2017, 1, 2, tzinfo=tz).utcoffset())

tz1 = pytz.timezone('Asia/Tokyo')
print(datetime(2017, 1, 2, tzinfo=tz1))

print(datetime(2017, 1, 2, tzinfo=tz1).utcoffset())

2017-01-02 00:00:00+08:28
8:28:00
2017-01-02 00:00:00+09:00
9:00:00


In [110]:
import pytz

print("Asia/Seoul" in pytz.all_timezones_set)
print("Asia/Seoul" in pytz.common_timezones)
print("Asia/Seoul" in pytz.common_timezones_set)


True
True
True


In [117]:
import pytz
import datetime

korean = pytz.timezone('Asia/Seoul')

print(type(korean))

print(" Asia/Seoul time zone ", korean.localize(datetime.datetime.now()))
korean_dt = korean.localize(datetime.datetime.now())
print("datatime.datetime.astimezone normalize ")
print("type ", korean_dt.astimezone(pytz.timezone('US/Eastern')))
eastern = korean_dt.astimezone(pytz.timezone('US/Eastern'))
print(" time zone change ", eastern)


<class 'pytz.tzfile.Asia/Seoul'>
 Asia/Seoul time zone  2017-01-02 11:21:45.494015+09:00
datatime.datetime.astimezone normalize 
type  2017-01-01 21:21:45.494015-05:00
 time zone change  2017-01-01 21:21:45.494015-05:00


In [118]:
import pytz
import datetime

print( "pytz.UTC ", type(pytz.UTC), pytz.UTC)
print( "pytz.UTC.zone ", type(pytz.UTC.zone), pytz.UTC.zone)
print( "pytz.UTC.tzname ", pytz.UTC.tzname)
print( "pytz.UTC formutc method ", pytz.UTC.fromutc(datetime.datetime.utcnow()))


pytz.UTC  <class 'pytz.UTC'> UTC
pytz.UTC.zone  <class 'str'> UTC
pytz.UTC.tzname  <bound method UTC.tzname of <UTC>>
pytz.UTC formutc method  2017-01-02 02:23:18.681715+00:00


In [119]:
import pytz
import datetime

utc = pytz.utc
print( "pytz.utc dst method ", utc.dst(datetime.datetime.utcnow()))
print( "pytz.utc utcoffset method ", utc.utcoffset(datetime.datetime.utcnow()))
print( "pytz.utc localize method ", utc.localize(datetime.datetime.utcnow()))
print("pytz.utc normalize method ", utc.normalize(datetime.datetime.now(tz=pytz.timezone("Asia/Seoul"))))


pytz.utc dst method  0:00:00
pytz.utc utcoffset method  0:00:00
pytz.utc localize method  2017-01-02 02:24:35.877315+00:00
pytz.utc normalize method  2017-01-02 02:24:35.877315+00:00


In [121]:
import pytz
import datetime

korean = pytz.timezone('Asia/Seoul')

print( type(korean))

print( " Asia/Seoul time zone ", korean.localize(datetime.datetime.now()))


<class 'pytz.tzfile.Asia/Seoul'>
 Asia/Seoul time zone  2017-01-02 11:25:59.278215+09:00


In [122]:
from datetime import datetime, timedelta
from pytz import timezone
import pytz
utc = pytz.utc
print(utc.zone)

eastern = timezone('US/Eastern')
print(eastern.zone)

amsterdam = timezone('Europe/Amsterdam')
fmt = '%Y-%m-%d %H:%M:%S %Z%z'

loc_dt = eastern.localize(datetime(2002, 10, 27, 6, 0, 0))
print(loc_dt.strftime(fmt))

UTC
US/Eastern
2002-10-27 06:00:00 EST-0500


In [123]:
type(eastern)

pytz.tzfile.US/Eastern

In [125]:
dir(eastern)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_dst',
 '_transition_info',
 '_tzinfos',
 '_tzname',
 '_utc_transition_times',
 '_utcoffset',
 'dst',
 'fromutc',
 'localize',
 'normalize',
 'tzname',
 'utcoffset',
 'zone']

In [138]:
from pytz import timezone
from datetime import datetime

korea = timezone('Asia/Seoul')
print(type(korea))
print(korea.tzname)
print(korea.utcoffset)
print(korea.zone)
loc_dt = korea.localize(datetime(2017,1,2))
print(loc_dt)
print(type(loc_dt))
print(korea.normalize(loc_dt))

<class 'pytz.tzfile.Asia/Seoul'>
<bound method DstTzInfo.tzname of <DstTzInfo 'Asia/Seoul' LMT+8:28:00 STD>>
<bound method DstTzInfo.utcoffset of <DstTzInfo 'Asia/Seoul' LMT+8:28:00 STD>>
Asia/Seoul
2017-01-02 00:00:00+09:00
<class 'datetime.datetime'>
2017-01-02 00:00:00+09:00


In [135]:
help(korea.normalize)

Help on method normalize in module pytz.tzinfo:

normalize(dt) method of pytz.tzfile.Asia/Seoul instance
    Correct the timezone information on the given datetime
    
    If date arithmetic crosses DST boundaries, the tzinfo
    is not magically adjusted. This method normalizes the
    tzinfo to the correct one.
    
    To test, first we need to do some setup
    
    >>> from pytz import timezone
    >>> utc = timezone('UTC')
    >>> eastern = timezone('US/Eastern')
    >>> fmt = '%Y-%m-%d %H:%M:%S %Z (%z)'
    
    We next create a datetime right on an end-of-DST transition point,
    the instant when the wallclocks are wound back one hour.
    
    >>> utc_dt = datetime(2002, 10, 27, 6, 0, 0, tzinfo=utc)
    >>> loc_dt = utc_dt.astimezone(eastern)
    >>> loc_dt.strftime(fmt)
    '2002-10-27 01:00:00 EST (-0500)'
    
    Now, if we subtract a few minutes from it, note that the timezone
    information has not changed.
    
    >>> before = loc_dt - timedelta(minutes=10)
    >>> 

In [140]:
from pytz import timezone
from datetime import datetime

th = timezone('Asia/Bangkok')
am = timezone('Europe/Amsterdam')
dt = th.localize(datetime(2011, 5, 7, 1, 2, 3))
print(dt)
fmt = '%Y-%m-%d %H:%M:%S %Z (%z)'
print(am.normalize(dt).strftime(fmt))


2011-05-07 01:02:03+07:00
2011-05-06 20:02:03 CEST (+0200)


In [141]:
from datetime import tzinfo, timedelta, datetime
from pytz import UTC


class MyUTCOffsetTimezone (tzinfo):

    def __init__(self, offset=19800, name=None):
        self.offset = timedelta(seconds=offset)
        self.name = name or self.__class__.__name__

    def utcoffset(self, dt):
        return self.offset

    def tzname(self, dt):
        return self.name

    def dst(self, dt):
        return timedelta(0)

now = datetime.now(tz=UTC)
print(now)

print(now.astimezone(MyUTCOffsetTimezone()))

print(datetime.now(MyUTCOffsetTimezone()))


2017-01-02 02:47:38.481446+00:00
2017-01-02 08:17:38.481446+05:30
2017-01-02 08:17:38.482446+05:30


In [146]:
from datetime import tzinfo

print(type(tzinfo))
print(dir(tzinfo))

i = tzinfo()
print(i)

<class 'type'>
['__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'dst', 'fromutc', 'tzname', 'utcoffset']


In [156]:
import datetime

tod = datetime.date.today()
todate = datetime.datetime.today()
print(type(tod), tod)

print(type(todate), todate)


<class 'datetime.date'> 2017-01-02
<class 'datetime.datetime'> 2017-01-02 12:03:42.651516


In [165]:
import datetime

tod = datetime.date.today()
print(tod.weekday())
print(tod.isoweekday())
print(tod.timetuple())
print(tod.replace(2020,3,30))

0
1
time.struct_time(tm_year=2017, tm_mon=1, tm_mday=2, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=0, tm_yday=2, tm_isdst=-1)
2020-03-30


In [162]:
import datetime

d1 = datetime.date(2016,2,3)
d2 = datetime.date.today()
dd = d2-d1
print(type(dd), dd)

print(d1 > d2)
print(d1 < d2)
d3 = d1 + dd
print(type(d3), d3)


<class 'datetime.timedelta'> 334 days, 0:00:00
False
True
<class 'datetime.date'> 2017-01-02


In [167]:
import datetime

d1 = datetime.date.today()
print(d1.toordinal())

print(d1.fromordinal(736331))


736331
2017-01-02


In [168]:
import datetime

#줄리안 데이트 구하기
def cal_julian(year,month,day) :
    start = datetime.date(year,month,day)
    print(' start day : ', start)
    end   = datetime.date.today()
    print( ' end   day : ', end)
    
    time_delta  = end - start
    print( ' julian day : ', time_delta.days)
    
    return (start,time_delta.days)
#시작일로부터 현재일자 변환     
def cal_ordinal(start) :
    x, y = cal_julian(1,1,1)
    ordinal = y  +1
    print( " today :", datetime.date.fromordinal(ordinal))
    

if __name__ == "__main__" :
    start,julian_day = cal_julian(2015,2,3)
    cal_ordinal(start)


 start day :  2015-02-03
 end   day :  2017-01-02
 julian day :  699
 start day :  0001-01-01
 end   day :  2017-01-02
 julian day :  736330
 today : 2017-01-02


In [185]:
import pytz

print(type(pytz.UTC))
print(pytz.UTC.__class__.__class__)
print(pytz.UTC.dst(datetime.datetime.today()))
print(pytz.UTC.localize(datetime.datetime.today()))
print(pytz.UTC.tzname(datetime.datetime.today()))
print(pytz.UTC.utcoffset(datetime.datetime.today()))
print(pytz.UTC.zone)


<class 'pytz.UTC'>
<class 'type'>
0:00:00
2017-01-02 12:41:23.985054+00:00
UTC
0:00:00
UTC


In [191]:
import datetime

print(type(datetime.tzinfo))
print(help(datetime.tzinfo))

<class 'type'>
Help on class tzinfo in module datetime:

class tzinfo(builtins.object)
 |  Abstract base class for time zone info objects.
 |  
 |  Methods defined here:
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.
 |  
 |  __reduce__(...)
 |      -> (cls, state)
 |  
 |  dst(...)
 |      datetime -> DST offset in minutes east of UTC.
 |  
 |  fromutc(...)
 |      datetime in UTC -> datetime in local time.
 |  
 |  tzname(...)
 |      datetime -> string name of time zone.
 |  
 |  utcoffset(...)
 |      datetime -> timedelta showing offset from UTC, negative values indicating West of UTC

None


In [197]:
import datetime

cdatetime = datetime.datetime.now() 
cdatetime.strftime("%d %b %Y %I:%M:%S %p") 

print(type(cdatetime), cdatetime)

dt = datetime.datetime.strptime('17 Feb 2009 04:22:11 PM','%d %b %Y %I:%M:%S %p') 
print(type(dt),dt)

<class 'datetime.datetime'> 2017-01-02 13:02:38.156684
<class 'datetime.datetime'> 2009-02-17 16:22:11


In [198]:
import datetime

d1 = datetime.datetime.today()
print(d1.toordinal())

print(d1.fromordinal(736331))


736331
2017-01-02 00:00:00


In [199]:
import datetime
print(datetime.datetime.now())
print(datetime.datetime.utcnow())
print(datetime.datetime.today())

2017-01-02 13:07:37.958914
2017-01-02 04:07:37.958914
2017-01-02 13:07:37.958915


In [201]:
import datetime

d1 = datetime.datetime.today()
print(d1.year)
print(d1.month)
print(d1.day)
print(d1.hour)
print(d1.minute)
print(d1.second)
print(d1.microsecond)
print(d1.tzinfo)

2017
1
2
13
11
23
855215
None


In [203]:
import datetime

print(datetime.datetime.min)
print(datetime.datetime.max)
print(datetime.datetime.resolution)


0001-01-01 00:00:00
9999-12-31 23:59:59.999999
0:00:00.000001


In [205]:
import datetime

cdatetime = datetime.date.today() 
cdatetime.strftime("%d %b %Y") 

print(type(cdatetime), cdatetime)

dt = cdatetime.isoformat() 
print(type(dt),dt)

<class 'datetime.date'> 2017-01-02
<class 'str'> 2017-01-02


In [210]:
import datetime
import time

cdatetime = datetime.date.today() 
print(type(cdatetime), cdatetime)

s = cdatetime.fromtimestamp(time.time())
print(type(s), s)


<class 'datetime.date'> 2017-01-02
<class 'datetime.date'> 2017-01-02


In [217]:
import time

s = time.ctime()
print(type(s), s)

d1 = time.time()
print(d1.hour)
print(d1.minute)
print(d1.second)
print(d1.microsecond)
print(d1.tzinfo)


Mon Jan  2 13:25:29 2017


AttributeError: 'str' object has no attribute 'min'

In [240]:
import datetime
loc = datetime.time(22,10,5)
print(loc)
print(loc.min, loc.max)
print(loc.hour)
print(loc.minute)
print(loc.second)

22:10:05
00:00:00 23:59:59.999999
22
10
5


In [230]:
dir(datetime.time)

['__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'dst',
 'hour',
 'isoformat',
 'max',
 'microsecond',
 'min',
 'minute',
 'replace',
 'resolution',
 'second',
 'strftime',
 'tzinfo',
 'tzname',
 'utcoffset']

In [241]:
from datetime import time, tzinfo,timedelta

#tzinfo 추상클래스를 현행화
class GMT1(tzinfo):
    def utcoffset(self, dt):
        return timedelta(hours=1)
    def dst(self, dt):
        return timedelta(0)
    def tzname(self,dt):
        return "Europe/Prague"
 
#시간생성  tzinfo에 객체 생성    
t = time(12, 10, 30, tzinfo=GMT1())
print( "time instance   : ",t)
print( "time iso format : ",t.isoformat())
print( "time dst        : ", t.dst())
print( 'time zone       : ',t.tzname())
print( "time strftime   : ",t.strftime("%H:%M:%S %Z"))
print( 'The {} is {:%H:%M}.'.format("time", t))


time instance   :  12:10:30+01:00
time iso format :  12:10:30+01:00
time dst        :  0:00:00
time zone       :  Europe/Prague
time strftime   :  12:10:30 Europe/Prague
The time is 12:10.


In [246]:
from datetime import tzinfo,timedelta
import datetime

class Zone(tzinfo):
    def __init__(self,offset,isdst,name):
        self.offset = offset
        self.isdst = isdst
        self.name = name
    def utcoffset(self, dt):
        return timedelta(hours=self.offset) + self.dst(dt)
    def dst(self, dt):
            return timedelta(hours=1) if self.isdst else timedelta(0)
    def tzname(self,dt):
         return self.name

GMT = Zone(0,False,'GMT')
EST = Zone(-5,False,'EST')

print( datetime.datetime.utcnow().strftime('%m/%d/%Y %H:%M:%S %Z'))
print( datetime.datetime.now(GMT).strftime('%m/%d/%Y %H:%M:%S %Z'))
print( datetime.datetime.now(EST).strftime('%m/%d/%Y %H:%M:%S %Z'))


01/02/2017 04:44:33 
01/02/2017 04:44:33 GMT
01/01/2017 23:44:33 EST


In [247]:
import datetime

now2 = datetime.datetime.now()

#오늘에 하루를 더해서 내일 구하기
tomorrow = now2 + datetime.timedelta(days=1)
print(tomorrow)                            


2017-01-03 13:49:43.826767


In [248]:

import datetime

oneDatetime = datetime.datetime.strptime('2015-04-15 00:00:00', '%Y-%m-%d %H:%M:%S')
twoDatetime = datetime.datetime.strptime('2015-04-16 00:00:10', '%Y-%m-%d %H:%M:%S')

result = twoDatetime - oneDatetime
print(result)                               
print(result.days)                      
print(result.seconds)                  

1 day, 0:00:10
1
10


In [250]:

import datetime
import pytz


tz = pytz.timezone('America/St_Johns')

st_johns_dt = tz.normalize(datetime.datetime.now(tz=pytz.utc))
print( " ameria / st_johns ", st_johns_dt)

print( " utc offset ",st_johns_dt.utcoffset())
st_tmdt = st_johns_dt.utcoffset()
print( int(st_tmdt.total_seconds()/3600) )
print( int((st_tmdt.total_seconds()%3600)/60) )


 ameria / st_johns  2017-01-02 01:22:14.207167-03:30
 utc offset  -1 day, 20:30:00
-3
30


In [252]:
from datetime import timedelta 

year = timedelta(days=365)
another_year = timedelta(weeks=40, days=84, hours=23,
                         minutes=50, seconds=600) # adds up to 365 days

print(year.total_seconds())
print(another_year.total_seconds())
print(year == another_year )


31536000.0
31536000.0
True


In [256]:
import pytz
from datetime import datetime

tz = pytz.timezone('Asia/Seoul')
d1 = datetime(2013, 2, 3, tzinfo=tz)

print(d1)
print(d1.utcoffset())

tz1 = pytz.timezone('US/Eastern') 
d2 = datetime(2013, 2, 3, tzinfo=tz1)

print(d2)
print(d2.utcoffset())

print(d1-d2)


2013-02-03 00:00:00+08:28
8:28:00
2013-02-03 00:00:00-04:56
-1 day, 19:04:00
-1 day, 10:36:00


In [267]:
import datetime
import time

a = datetime.datetime.fromtimestamp(time.time())
print(a)

b = datetime.datetime.combine(datetime.date.today(), datetime.time(22,22,22))
print(b)

2017-01-02 14:17:35.142168
2017-01-02 22:22:22


In [268]:
import time
print(time.time())

1483335391.0532677


In [269]:
help(time.time)

Help on built-in function time in module time:

time(...)
    time() -> floating point number
    
    Return the current time in seconds since the Epoch.
    Fractions of a second may be present if the system clock provides them.



In [270]:
dir(time)

['_STRUCT_TM_ITEMS',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'altzone',
 'asctime',
 'clock',
 'ctime',
 'daylight',
 'get_clock_info',
 'gmtime',
 'localtime',
 'mktime',
 'monotonic',
 'perf_counter',
 'process_time',
 'sleep',
 'strftime',
 'strptime',
 'struct_time',
 'time',
 'timezone',
 'tzname']

In [293]:
import time

a = time.localtime()
print(a)

b = time.mktime(a)
print(b)


time.struct_time(tm_year=2017, tm_mon=1, tm_mday=2, tm_hour=15, tm_min=2, tm_sec=38, tm_wday=0, tm_yday=2, tm_isdst=0)
1483336958.0


In [280]:
print(time.altzone)

-36000


In [273]:
import time
print(time.ctime())

Mon Jan  2 14:41:28 2017


In [274]:
help(time.ctime)

Help on built-in function ctime in module time:

ctime(...)
    ctime(seconds) -> string
    
    Convert a time in seconds since the Epoch to a string in local time.
    This is equivalent to asctime(localtime(seconds)). When the time tuple is
    not present, current time as returned by localtime() is used.



In [282]:
import time

localtime = time.localtime(time.time())
print(localtime)

time.struct_time(tm_year=2017, tm_mon=1, tm_mday=2, tm_hour=14, tm_min=48, tm_sec=41, tm_wday=0, tm_yday=2, tm_isdst=0)


In [285]:
print(time.timezone)
print(time.tzname)

-32400
('´ëÇѹα¹ Ç¥ÁؽÃ', '´ëÇѹα¹ Àϱ¤ Àý¾à ½Ã°£')


In [298]:
import pytz
# local time 구하기
# 서울 date time 구하기
seoul_tz = pytz.timezone('Asia/Seoul')
print( " seoul time zone ",seoul_tz)
seoul_dt = seoul_tz.localize(datetime.datetime.now())
print( " seoul datetime ", seoul_dt)

# 평양 date time으로  구하기
pyongyang_tz = pytz.timezone('Asia/Pyongyang')
print( " pyongyang time zone ", pyongyang_tz)
pyongyang_dt = pyongyang_tz.localize(datetime.datetime.now())
print( " pyongyang datetime ", pyongyang_dt)

 seoul time zone  Asia/Seoul
 seoul datetime  2017-01-02 15:09:42.038008+09:00
 pyongyang time zone  Asia/Pyongyang
 pyongyang datetime  2017-01-02 15:09:42.039008+08:30


In [307]:
import pytz

# 평양 date time으로  구하기
pyongyang_tz = pytz.timezone('Asia/Pyongyang')
pyongyang_dt = pyongyang_tz.localize(datetime.datetime.now())
print( " pyongyang datetime ", pyongyang_dt)
before = pyongyang_tz.normalize(pyongyang_dt - datetime.timedelta(minutes=30))
print( " 실제 평양 시간 조정 ", before)


 pyongyang datetime  2017-01-02 15:20:31.744508+08:30
 실제 평양 시간 조정  2017-01-02 14:50:31.744508+08:30


In [311]:
import pytz

# 평양 date time으로  구하기
pyongyang_tz = pytz.timezone('Asia/Pyongyang')
pyongyang_dt = pyongyang_tz.localize(datetime.datetime.now())
print(type(pyongyang_dt))
print( " pyongyang datetime ", pyongyang_dt)
# 평양 date time를 UTC로 구하기
print("기준시간 : ", datetime.datetime.now(tz=pytz.utc))
after = pyongyang_tz.normalize(datetime.datetime.now(tz=pytz.utc))
print( " 실제 평양시간 조정", after)

<class 'datetime.datetime'>
 pyongyang datetime  2017-01-02 15:30:29.974808+08:30
기준시간 :  2017-01-02 06:30:29.974808+00:00
 실제 평양시간 조정 2017-01-02 15:00:29.974808+08:30


 pyongyang datetime  2017-01-02 15:27:54.532708+08:30
기준시간 :  2017-01-02 06:27:54.532708+00:00
2017-01-02 15:27:54.532708+08:30


In [312]:
import pytz
import datetime

korean = pytz.timezone('Asia/Seoul')
print(" Asia/Seoul time zone ", korean.localize(datetime.datetime.now()))
korean_dt = korean.localize(datetime.datetime.now())

print("datatime.datetime.astimezone normalize ")
eastern = pytz.timezone('US/Eastern')
print("type ", korean_dt.astimezone(pytz.timezone('US/Eastern')))
eastern = korean_dt.astimezone(pytz.timezone('US/Eastern'))
print(" time zone change ", eastern)

<class 'pytz.tzfile.Asia/Seoul'>
 Asia/Seoul time zone  2017-01-02 15:31:09.387008+09:00
datatime.datetime.astimezone normalize 
type  2017-01-02 01:31:09.387008-05:00
 time zone change  2017-01-02 01:31:09.387008-05:00


In [316]:
import pytz

for tz in pytz.all_timezones_set :
    if "Asia" in tz :
        print(tz)

Asia/Bishkek
Asia/Barnaul
Asia/Aqtobe
Asia/Srednekolymsk
Asia/Harbin
Asia/Taipei
Asia/Baku
Asia/Yakutsk
Asia/Vientiane
Asia/Gaza
Asia/Calcutta
Asia/Shanghai
Asia/Tokyo
Asia/Yerevan
Asia/Sakhalin
Asia/Dhaka
Asia/Jerusalem
Asia/Omsk
Asia/Kabul
Asia/Kamchatka
Asia/Almaty
Asia/Nicosia
Asia/Hovd
Asia/Rangoon
Asia/Macau
Asia/Singapore
Asia/Riyadh
Asia/Istanbul
Asia/Amman
Asia/Katmandu
Asia/Hong_Kong
Asia/Kuala_Lumpur
Asia/Seoul
Asia/Thimbu
Asia/Saigon
Asia/Bangkok
Asia/Ulaanbaatar
Asia/Choibalsan
Asia/Qyzylorda
Asia/Pyongyang
Asia/Karachi
Asia/Phnom_Penh
Asia/Oral
Asia/Hebron
Asia/Dacca
Asia/Chungking
Asia/Tomsk
Asia/Chongqing
Asia/Damascus
Asia/Khandyga
Asia/Kolkata
Asia/Bahrain
Asia/Dili
Asia/Jakarta
Asia/Makassar
Asia/Chita
Asia/Magadan
Asia/Brunei
Asia/Thimphu
Asia/Kuching
Asia/Macao
Asia/Ulan_Bator
Asia/Krasnoyarsk
Asia/Qatar
Asia/Jayapura
Asia/Pontianak
Asia/Kathmandu
Asia/Novosibirsk
Asia/Aden
Asia/Tehran
Asia/Beirut
Asia/Baghdad
Asia/Tashkent
Asia/Dubai
Asia/Ho_Chi_Minh
Asia/Tbilisi


In [332]:
import pytz
import datetime

# 타임존을 만들고
a = pytz.timezone('Asia/Seoul')
# datetime을 넣고 타임존에 맞춰 datetime을 생성
print(datetime.datetime.now().tzinfo)
asloct = a.localize(datetime.datetime.now())
print(type(asloct), asloct.tzinfo)

#utc 시간으로 생성
asloct1 = a.localize(datetime.datetime.utcnow())
print(asloct1)

b = pytz.timezone('Asia/Tokyo')
#normalize는 tzinfo가 setting 된 경우만 처리됨
print(b.normalize(asloct))
print(b.normalize(b.localize(datetime.datetime.now())))

None
<class 'datetime.datetime'> Asia/Seoul
2017-01-02 07:17:55.764219+09:00
2017-01-02 16:17:55.764219+09:00
2017-01-02 16:17:55.764219+09:00


In [337]:
import time 

a = time.localtime()
print(time.asctime(a))
print(time.asctime())

Mon Jan  2 16:36:38 2017
Mon Jan  2 16:36:38 2017


In [338]:
'\u1100'

'ᄀ'

In [353]:
import unicodedata

ki = unicodedata.name('\u1100')
print(ki)
print(unicodedata.lookup(ki))
print(unicodedata.decimal('\u0031',"?"))
print(unicodedata.decimal('\u1100',"?"))
print(unicodedata.category('\u1100'))
print(unicodedata.category('\u0031'))

HANGUL CHOSEONG KIYEOK
ᄀ
1
?
Lo
Nd


In [374]:
import unicodedata

print(unicodedata.category('a'))
print(unicodedata.category('A'))
print(unicodedata.category('\u1100'))
ki = unicodedata.name('\u1100')
print(ki)
print(unicodedata.lookup(ki))

Ll
Lu
Lo
HANGUL CHOSEONG KIYEOK
ᄀ


In [365]:
print(unicodedata.category('\u0031'))
ki = unicodedata.name('\u0031')
print(ki)
print(unicodedata.lookup(ki))


Nd
DIGIT ONE
1


In [372]:
import unicodedata
print(unicodedata.category('\u001B'))


Cc


In [381]:
print(unicodedata.category('\u0020'))
print(unicodedata.category('\u00A0'))
ki = unicodedata.name('\u00A0')
print(ki)
print(unicodedata.lookup(ki))

Zs
Zs
NO-BREAK SPACE
 


In [384]:

print(unicodedata.category('\U00010023'))
ki = unicodedata.name('\U00010023')
print(ki)
print(unicodedata.lookup(ki))

Lo
LINEAR B SYLLABLE B016 QA
𐀣


In [378]:
ki = unicodedata.name('강')
print(ki)
print(unicodedata.lookup(ki))
unicodedata.decomposition("가")

HANGUL SYLLABLE GANG
강


''

In [414]:
import unicodedata

s = '\uc704'
ki = unicodedata.name(s)
print(ki)
print(unicodedata.lookup(ki))
x = unicodedata.normalize('NFD',s)
print(len(s), s.encode("utf-8"))
print(len(x), x.encode("utf-8"))

cx = unicodedata.normalize('NFC',x)
print(len(x), x.encode("utf-8"))
print(len(cx), cx.encode("utf-8"))

HANGUL SYLLABLE WI
위
1 b'\xec\x9c\x84'
2 b'\xe1\x84\x8b\xe1\x85\xb1'
2 b'\xe1\x84\x8b\xe1\x85\xb1'
1 b'\xec\x9c\x84'


In [422]:
help(unicodedata.decomposition)

Help on built-in function decomposition in module unicodedata:

decomposition(chr, /)
    Returns the character decomposition mapping assigned to the character chr as string.
    
    An empty string is returned in case no such mapping is defined.



In [432]:
s = '\u1F00'
ki = unicodedata.name(s)
print(ki)
print(unicodedata.lookup(ki))
x = unicodedata.decomposition(s)
print(len(s), s)
print(len(x), x)
ki = unicodedata.name("\u03B1")
print(ki)
print(unicodedata.lookup(ki))
ki = unicodedata.name("\u0313")
print(ki)
print(unicodedata.lookup(ki))

GREEK SMALL LETTER ALPHA WITH PSILI
ἀ
1 ἀ
9 03B1 0313
GREEK SMALL LETTER ALPHA
α
COMBINING COMMA ABOVE
̓


In [400]:
print('%r' % unicodedata.normalize('NFKD','\uc704'))

'위'


In [421]:
s1 = '\u1E9B'
t1 = unicodedata.normalize('NFKC', s1)
print(len(s1), s1)
print(s1.encode("utf-8"))
print(len(t1),t1)
print(t1.encode("utf-8"))


1 ẛ
b'\xe1\xba\x9b'
1 ṡ
b'\xe1\xb9\xa1'


In [411]:
s1 = 'Spicy Jalape\u00f1o'
t1 = unicodedata.normalize('NFD', s1)
print(len(s1))
print(s1.encode("utf-8"))
print(len(t1))
print(t1.encode("utf-8"))

14
b'Spicy Jalape\xc3\xb1o'
15
b'Spicy Jalapen\xcc\x83o'


In [435]:
precomposed = "\u1F00"
decomposed  = "\u03B1\u0313"

s1 = unicodedata.normalize("NFC", precomposed) 
s2 = unicodedata.normalize("NFC", decomposed)
print(s1,s2)
s3 = unicodedata.normalize("NFD", precomposed)
s4 = unicodedata.normalize("NFD", decomposed)
print(s3,s4)
print(s3.encode("utf-8"))
print(s4.encode("utf-8"))

ἀ ἀ
ἀ ἀ
b'\xce\xb1\xcc\x93'
b'\xce\xb1\xcc\x93'


In [439]:
help(unicodedata.decomposition)

Help on built-in function decomposition in module unicodedata:

decomposition(chr, /)
    Returns the character decomposition mapping assigned to the character chr as string.
    
    An empty string is returned in case no such mapping is defined.



In [436]:
help(unicodedata.combining)

Help on built-in function combining in module unicodedata:

combining(chr, /)
    Returns the canonical combining class assigned to the character chr as integer.
    
    Returns 0 if no combining class is defined.



In [437]:
import unicodedata

if unicodedata.combining('a'):
    print("is combining character")
else:
    print("is not combining")

is not combining


In [440]:
import unicodedata

if unicodedata.combining('\u0343'):
    print("is combining character")
else:
    print("is not combining")
    
print(unicodedata.combining('\u0343')) 

is combining character
230


In [454]:
s = '\u00f1'
print(unicodedata.combining(s)) 
print(len(s), s, s.encode("utf-8"))
ss = unicodedata.normalize('NFD', s)
print(len(ss),ss,ss.encode("utf-8"))

s1 = 'Spicy Jalape\u00f1o'
t1 = unicodedata.normalize('NFD', s1)
print(len(s1))
print(s1.encode("utf-8"))
print(len(t1))
print(t1.encode("utf-8"))

0
1 ñ b'\xc3\xb1'
2 ñ b'n\xcc\x83'
14
b'Spicy Jalape\xc3\xb1o'
15
b'Spicy Jalapen\xcc\x83o'


In [457]:
just_len = 40
s1 = 'Jalapen\u0303o'
s2 = 'Jalape\u00f1o'
t1 = unicodedata.normalize('NFC', s1)
t2 = unicodedata.normalize('NFC', s2)
print('NFC means normal form composed'.ljust(just_len),
      t1, t2, len(t1), len(t2), t1 == t2)

NFC means normal form composed           Jalapeño Jalapeño 8 8 True


In [459]:
just_len = 40
s1 = 'Jalapen\u0303o'
s2 = 'Jalape\u00f1o'
t1 = unicodedata.normalize('NFD', s1)
t2 = unicodedata.normalize('NFD', s2)
print('NFD means normal form decomposed'.ljust(just_len),
      t1, t2, len(t1), len(t2), t1 == t2)

NFD means normal form decomposed         Jalapeño Jalapeño 9 9 True


In [465]:
just_len = 40
t1 = unicodedata.normalize('NFKD', '\u2160')
t2 = unicodedata.normalize('NFKD', '\u0049')
print('NFKD means normal form compatible decomposed'.ljust(just_len),
      t1, t2, len(t1), len(t2), t1 == t2)
print('\u2160','\u0049','\u2160'== '\u0049' )
print(t1.encode("utf-8"), t2.encode("utf-8"))

NFKD means normal form compatible decomposed I I 1 1 True
Ⅰ I
b'I' b'I'


In [467]:
just_len = 40
t1 = unicodedata.normalize('NFKD', '\u2160')
t2 = unicodedata.normalize('NFKD', '\u0049')
print('NFKC means normal form compatible composed'.ljust(just_len),
      t1, t2, len(t1), len(t2), t1 == t2)
print('\u2160','\u0049','\u2160'== '\u0049' )
print(t1.encode("utf-8"), t2.encode("utf-8"))

NFKC means normal form compatible composed I I 1 1 True
Ⅰ I False
b'I' b'I'


In [477]:
# U+0000부터 U+007F
s= '\u0031'
ki = unicodedata.name(s)
print(ki)
print("1 bytes ",s, s.encode("utf-8"))

s2 = '\u0180'
ki = unicodedata.name(s2)
print(ki)
print("2 bytes ",s2, s2.encode("utf-8"))

s3 = '\uac10'
ki = unicodedata.name(s3)
print(ki)
print("3 bytes ",s3, s3.encode("utf-8"))

s4 = '\U00011100'
ki = unicodedata.name(s4)
print(ki)
print("4 bytes ",s4, s4.encode("utf-8"))

DIGIT ONE
1 bytes  1 b'1'
LATIN SMALL LETTER B WITH STROKE
2 bytes  ƀ b'\xc6\x80'
HANGUL SYLLABLE GAM
3 bytes  감 b'\xea\xb0\x90'
CHAKMA SIGN CANDRABINDU
4 bytes  𑄀 b'\xf0\x91\x84\x80'


In [480]:
import unicodedata

s= '\u0031'
ki = unicodedata.name(s)
print(ki)
print(unicodedata.lookup(ki))

s= '\u0250'
ki = unicodedata.name(s)
print(ki)
print(unicodedata.lookup(ki))

s= '\u0370'
ki = unicodedata.name(s)
print(ki)
print(unicodedata.lookup(ki))

DIGIT ONE
1
LATIN SMALL LETTER TURNED A
ɐ
GREEK CAPITAL LETTER HETA
Ͱ


In [485]:
# U+0000부터 U+007F
s= '\u0031'
ki = unicodedata.name(s)
print(ki)
print(len(s.encode("utf-16"))," bytes ",s, s.encode("utf-16"))

s2 = '\u0180'
ki = unicodedata.name(s2)
print(ki)
print(len(s2.encode("utf-16"))," bytes ",s2, s2.encode("utf-16"))

s3 = '\uac10'
ki = unicodedata.name(s3)
print(ki)
print(len(s3.encode("utf-16"))," bytes ",s3, s3.encode("utf-16"))

s4 = '\U00011100'
ki = unicodedata.name(s4)
print(ki)
print(len(s4.encode("utf-16"))," bytes ",s4, s4.encode("utf-16"))

DIGIT ONE
4  bytes  1 b'\xff\xfe1\x00'
LATIN SMALL LETTER B WITH STROKE
4  bytes  ƀ b'\xff\xfe\x80\x01'
HANGUL SYLLABLE GAM
4  bytes  감 b'\xff\xfe\x10\xac'
CHAKMA SIGN CANDRABINDU
6  bytes  𑄀 b'\xff\xfe\x04\xd8\x00\xdd'


In [486]:
# U+0000부터 U+007F
s= '\u0031'
ki = unicodedata.name(s)
print(ki)
print(len(s.encode("utf-32"))," bytes ",s, s.encode("utf-32"))

s2 = '\u0180'
ki = unicodedata.name(s2)
print(ki)
print(len(s2.encode("utf-32"))," bytes ",s2, s2.encode("utf-32"))

s3 = '\uac10'
ki = unicodedata.name(s3)
print(ki)
print(len(s3.encode("utf-32"))," bytes ",s3, s3.encode("utf-32"))

s4 = '\U00011100'
ki = unicodedata.name(s4)
print(ki)
print(len(s4.encode("utf-32"))," bytes ",s4, s4.encode("utf-32"))

DIGIT ONE
8  bytes  1 b'\xff\xfe\x00\x001\x00\x00\x00'
LATIN SMALL LETTER B WITH STROKE
8  bytes  ƀ b'\xff\xfe\x00\x00\x80\x01\x00\x00'
HANGUL SYLLABLE GAM
8  bytes  감 b'\xff\xfe\x00\x00\x10\xac\x00\x00'
CHAKMA SIGN CANDRABINDU
8  bytes  𑄀 b'\xff\xfe\x00\x00\x00\x11\x01\x00'


In [492]:
s= '\u07ff'
sb = s.encode("utf-8")
print(sb)
print(bin(sb[0]), bin(sb[1]))

t= '\uffff'
tb = t.encode("utf-8")
print(tb)
print(bin(tb[0]), bin(tb[1]), bin(tb[2]))

b'\xdf\xbf'
0b11011111 0b10111111
b'\xef\xbf\xbf'
0b11101111 0b10111111 0b10111111


In [497]:
s= '\u07ff'
sb = s.encode("utf-32")
print(sb)
print(bin(sb[4]), bin(sb[5]))

t= '\uffff'
tb = t.encode("utf-32")
print(tb)
print(bin(tb[4]), bin(tb[5]))

b'\xff\xfe\x00\x00\xff\x07\x00\x00'
0b11111111 0b111
b'\xff\xfe\x00\x00\xff\xff\x00\x00'
0b11111111 0b11111111


In [498]:
dir(unicodedata)

['UCD',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'bidirectional',
 'category',
 'combining',
 'decimal',
 'decomposition',
 'digit',
 'east_asian_width',
 'lookup',
 'mirrored',
 'name',
 'normalize',
 'numeric',
 'ucd_3_2_0',
 'ucnhash_CAPI',
 'unidata_version']

In [499]:
help(unicodedata.mirrored)

Help on built-in function mirrored in module unicodedata:

mirrored(chr, /)
    Returns the mirrored property assigned to the character chr as integer.
    
    Returns 1 if the character has been identified as a "mirrored"
    character in bidirectional text, 0 otherwise.



In [501]:
unicodedata.mirrored('\uFFFF')

0

In [533]:
import unicodedata
s = '四'
ki = unicodedata.name(s)
print(ki, s.encode("utf-16"))
print(unicodedata.lookup(ki))

s1 = '\u56db'
ki = unicodedata.name(s1)
print(ki, s1.encode("utf-16"))
print(unicodedata.lookup(ki))

print(unicodedata.numeric('四', None))
print(unicodedata.numeric('8', None))

print(unicodedata.digit('四', None))
print(unicodedata.digit('8', None))

print(unicodedata.decimal('7'))
print(unicodedata.decimal('四', None))

CJK UNIFIED IDEOGRAPH-56DB b'\xff\xfe\xdbV'
四
CJK UNIFIED IDEOGRAPH-56DB b'\xff\xfe\xdbV'
四
4.0
8.0
None
8
7
None


In [509]:
hex(ord('V'))

'0x56'

In [510]:
print('\u56db')

四


In [513]:
import unicodedata
 
print(unicodedata.bidirectional('9'))
print(unicodedata.bidirectional('\u0660'))
print(unicodedata.bidirectional('中'))
print(unicodedata.bidirectional('a'))

EN
AN
L
L


In [517]:
help(unicodedata.bidirectional)

Help on built-in function bidirectional in module unicodedata:

bidirectional(chr, /)
    Returns the bidirectional class assigned to the character chr as string.
    
    If no such value is defined, an empty string is returned.



In [515]:
import unicodedata
 
print(unicodedata.mirrored('9'))
print(unicodedata.mirrored('A'))
print(unicodedata.mirrored('蔡'))

0
0
0


In [526]:
import unicodedata
s1 = '\u30AC'
ki = unicodedata.name(s1)
print(ki, s1.encode("utf-32"))
print(unicodedata.lookup(ki))

print(unicodedata.decomposition('9'))
print(unicodedata.decomposition('-'))
print(unicodedata.decomposition('蔡'))
print(unicodedata.decomposition('ガ'))
print('\u30AB', '\u3099' )
print('\u30AC' )

KATAKANA LETTER GA b'\xff\xfe\x00\x00\xac0\x00\x00'
ガ



30AB 3099
カ ゙
ガ


In [529]:
hex(ord('0'))

'0x30'

In [521]:
s1 = 'ガ'
ki = unicodedata.name(s1)
print(ki, s1.encode("utf-16"))
print(unicodedata.lookup(ki))

KATAKANA LETTER GA b'\xff\xfe\xac0'
ガ


In [522]:
print('\u30AB', '\u3099' )

カ ゙


In [523]:
print('\u30Ac' )

ガ


In [530]:
import unicodedata
 
print(unicodedata.east_asian_width('9'))
print(unicodedata.east_asian_width('A'))
print(unicodedata.east_asian_width('蔡'))

Na
Na
W


In [532]:
import unicodedata
 
print(unicodedata.unidata_version)
print(unicodedata.ucd_3_2_0)

8.0.0


In [534]:
import binascii

line = '000A0033002004200430043404300440000A003400200417043D0430043A043E043C0441044204320430000A00350020041C04430437044B043A0430000A00380020041504490435'
binascii.unhexlify(line)
b'\x00\n\x003\x00 \x04 \x040\x044\x040\x04@\x00\n\x004\x00 \x04\x17\x04=\x040\x04:\x04>\x04<\x04A\x04B\x042\x040\x00\n\x005\x00 \x04\x1c\x04C\x047\x04K\x04:\x040\x00\n\x008\x00 \x04\x15\x04I\x045'
print(binascii.unhexlify(line).decode('utf-16-be'))



3 Радар
4 Знакомства
5 Музыка
8 Еще


In [555]:
# UTF-16BE (Unicode Transformation Format - 16-bit Big Endian) 
biline = b'000A0033002004200430043404300440000A'
print(len(biline))
hexline = binascii.unhexlify(biline)
print(len(hexline), hexline)
print(hexline.decode('utf-16-be'))

36
18 b'\x00\n\x003\x00 \x04 \x040\x044\x040\x04@\x00\n'

3 Радар



In [558]:
# UTF-16BE (Unicode Transformation Format - 16-bit little Endian)
biline = b'000A0033002004200430043404300440000A'
print(binascii.unhexlify(biline))
print(binascii.unhexlify(biline).decode('utf-16-le'))

b'\x00\n\x003\x00 \x04 \x040\x044\x040\x04@\x00\n'
਀㌀  〄㐄〄䀄਀


In [578]:
s = 'BobDylan'
print(s.encode('euc-kr'))
print(hex(ord('B')))
#0x420x6F0x62 0x20 0x44 0x79 0x6C 0x6F 0x6E

b'BobDylan'
0x42


In [571]:
bs = b'01000010011011110110001000010100'
hexline = binascii.hexlify(bs)
print(hexline)
print(binascii.unhexlify(hexline).decode('utf-16-be'))

b'3031303030303130303131303131313130313130303031303030303130313030'
〱〰〰㄰〱㄰ㄱㄱ〱㄰〰㄰〰〱〱〰


In [579]:
import sys
sys.maxunicode

1114111

In [586]:
import binascii

# ucs-2-be
line1 = '000A0033002004200430043404300440000A003400200417043D0430043A'
line2 = '043E043C0441044204320430000A00350020041C04430437044B043A0430000A00380020041504490435'

# hex로 전환
unhex = binascii.unhexlify(line1+line2)
print(unhex)
#utf-16-be 변환
print(binascii.unhexlify(line1+line2).decode('utf-16-be'))


b'\x00\n\x003\x00 \x04 \x040\x044\x040\x04@\x00\n\x004\x00 \x04\x17\x04=\x040\x04:\x04>\x04<\x04A\x04B\x042\x040\x00\n\x005\x00 \x04\x1c\x04C\x047\x04K\x04:\x040\x00\n\x008\x00 \x04\x15\x04I\x045'

3 Радар
4 Знакомства
5 Музыка
8 Еще


In [592]:
line1 = b'\x00\n\x003\x00 \x04 \x040\x044\x040\x04@\x00\n\x004\x00 \x04\x17\x04=\x040\x04:\x04>\x04<'
line2 = b'\x04A\x04B\x042\x040\x00\n\x005\x00 \x04\x1c\x04C\x047\x04K\x04:\x040\x00\n\x008\x00 \x04\x15\x04I\x045'

print((line1+line2).decode('utf-16-be'))



3 Радар
4 Знакомства
5 Музыка
8 Еще


In [583]:
help(binascii.unhexlify)

Help on built-in function unhexlify in module binascii:

unhexlify(hexstr, /)
    Binary data of hexadecimal representation.
    
    hexstr must contain an even number of hex digits (upper or lower case).



In [584]:
help(binascii.hexlify)

Help on built-in function hexlify in module binascii:

hexlify(data, /)
    Hexadecimal representation of binary data.
    
    The return value is a bytes object.



In [599]:
print(str(b'\x00\xd8\x00\xdc', 'utf-16le'))
print(str(b'\xd8\x00\xdc\x00', 'utf-16be'))
print('\U00010000')
print('\U00010000'.encode('utf-16le'))
print('\U00010000'.encode('utf-16be'))
print('\U00010000'.encode('utf-16'))

𐀀
𐀀
𐀀
b'\x00\xd8\x00\xdc'
b'\xd8\x00\xdc\x00'
b'\xff\xfe\x00\xd8\x00\xdc'


In [602]:
print('\U0010FFFF')
print('\U0010FFFF'.encode('utf-8'))
print('\U0010FFFF'.encode('utf-16'))
print('\U0010FFFF'.encode('utf-32'))

􏿿
b'\xf4\x8f\xbf\xbf'
b'\xff\xfe\xff\xdb\xff\xdf'
b'\xff\xfe\x00\x00\xff\xff\x10\x00'


In [607]:
import glob
print(glob.glob('./[a-z].*'))

['.\\f.txt']


In [608]:
import glob
print(glob.glob('*.txt'))

['arraystore.txt', 'data.txt', 'data1.txt', 'f.txt', 'f2.txt', 'fil.txt', 'printfile.txt', 'somefile.txt']


In [609]:
import glob
pathList  = glob.iglob("*")
print(pathList)

for path in pathList : 
    print(path)

<generator object _iglob at 0x000000000593C780>
add_a_workbook.xlsx
arraystore.nd
arraystore.npy
arraystore.txt
bdsc4j.csv.xlsx
BeautifulSoup_test_20170120.ipynb
bs4_google_20170130.ipynb
country_data.xml
data.bin
data.txt
data.txt1
data1.bin
data1.txt
date_time_test_20170130.ipynb
decoraotor_test_20161030.ipynb
desktop.ini
dic_file.csv
dic_file1.csv
doc1.xml
ezPDFReader2.0
f
f.txt
f2.txt
fil.txt
file_test2_20170130.ipynb
file_test_20170130.ipynb
file_txt
file_txt1
fr.bin
fr.hex
fw
fw.bin
GitHub
homemade.xml
import_worker
import_worker.py
index.html
json_myobj.py
lxml_test.xml
matplotlib_test_20161110.ipynb
mp_sample.py
mp_sample1.py
multi_test.py
My Music
My Pictures
My Videos
myfile.html
note.xml
numpy_20161110.ipynb
numpy_test_20161115.ipynb
page.xhtml
pandas test_20161110.ipynb
persons.csv
persons1.csv
plugin-descriptor.properties
pool_map.py
pool_map1.py
printfile.bin
printfile.txt
Processing
process_apply.py
process_applyasync.py
process_daemon.py
process_daemon1.py
process_main.

In [615]:
import binascii

s = "hello"
# byte --> binary hex
a = binascii.hexlify(s.encode('utf-8'))
print(a)
# binary hex --> bytes
b = binascii.unhexlify(a)
print(b)
print(b == s)
# bytes --> unicode type
print(b.decode('utf-8') == s)

b'68656c6c6f'
b'hello'
False
True


In [625]:
import binascii

s = "hello"
# byte --> binary hex

a = binascii.hexlify(s.encode('utf-8'))
print(a)
# binary hex --> ucs 변환 유사
print(b'68656c6c6f')
b = binascii.unhexlify(a)
print(b)
#bytes hex
print(b'\x68\x65\x6c\x6c\x6f')
print(b.decode('utf-8'))
print(b.decode('utf-8').encode('utf-8'))


b'68656c6c6f'
b'68656c6c6f'
b'hello'
b'hello'
hello
b'hello'


In [647]:
import binascii


# byte --> binary hex
#a = binascii.hexlify(b'\xff\xfe\x00\x00\x31\x00\x32\x00')
a = binascii.hexlify(b'\x31\x00\x32\x00')
print(a)
# binary hex --> byte
b = binascii.unhexlify(a)
print(b)
print(b.decode('utf-8'))

b'31003200'
b'1\x002\x00'
12


In [648]:
import binascii

# byte --> binary hex
a = binascii.hexlify(b'\x00\x31\x00\x32')
print(a)
# binary hex --> byte
b = binascii.unhexlify(a)
print(b)
print(b.decode('utf-8'))

b'00310032'
b'\x001\x002'
12


In [655]:
s = '1'
  
print("utf-8    ", s.encode('utf-8'))

print("utf-16   ",s.encode('utf-16'))
print("utf-16le ",s.encode('utf-16le'))
print("utf-16be ",s.encode('utf-16be'))

print("utf-32   ",s.encode('utf-32'))
print("utf-32ie ",s.encode('utf-32le'))
print("utf-32be ",s.encode('utf-32be'))

utf-8     b'1'
utf-16    b'\xff\xfe1\x00'
utf-16le  b'1\x00'
utf-16be  b'\x001'
utf-32    b'\xff\xfe\x00\x001\x00\x00\x00'
utf-32ie  b'1\x00\x00\x00'
utf-32be  b'\x00\x00\x001'


In [661]:
num = '12'
print(num.encode("utf-16"))

s = b'\xfe\xff\x00\x31\x00\x32'

#\xfe\xff 이 값에 대해 해석이 불가
print(s[2:].decode("utf-8"))

# big endian
print(s.decode("utf-16be"))
print(s.decode("utf-16le"))

# little endian
s = b'\xff\xfe\x31\x00\x32\x00'
print(s.decode("utf-16be"))
print(s.decode("utf-16le"))

b'\xff\xfe1\x002\x00'
12
12
￾㄀㈀
￾㄀㈀
12


In [662]:
a = 0x8081
b = 0x0000
sa = str(a)
print(sa)

32897


In [682]:
import binascii

a = b'\x61\x00\x62\x00'
print(a)
print(a.decode("utf-8"))
print(a.decode("utf-16"))
b = b'\x61\x62'
print(b.decode("utf-8"))

c = "가을"
ce = c.encode("utf-16")
print(ce)
ucs2_ce = binascii.hexlify(ce[2:])
print(ucs2_ce)
ucs2_ced = binascii.unhexlify(ucs2_ce)
print(len(ucs2_ced), ucs2_ced)
print(ucs2_ced.decode("utf-16"))

ucs2 = '61006200'
print(type(ucs2))
d = binascii.unhexlify(ucs2)
print(len(d), d)
print(d.decode("utf-8"))

b'a\x00b\x00'
ab
ab
ab
b'\xff\xfe\x00\xacD\xc7'
b'00ac44c7'
4 b'\x00\xacD\xc7'
가을
<class 'str'>
4 b'a\x00b\x00'
ab


In [667]:
hex(ord('a'))

'0x61'

In [686]:
import binascii

c = "가을"
ce = c.encode("utf-16")
print(ce)
#ucs2로 전환-> hex 문자열로 생성
ucs2_ce = binascii.hexlify(ce[2:])
print(ucs2_ce)
#hex문자열을 bytes 문자열로 전환
ucs2_ced = binascii.unhexlify(ucs2_ce)
print(len(ucs2_ced), ucs2_ced)
#utf로 전환
print(ucs2_ced.decode("utf-16"))

b'\xff\xfe\x00\xacD\xc7'
b'00ac44c7'
4 b'\x00\xacD\xc7'
가을


In [685]:
import binascii
#hex문자열을 bytes 문자열로 전환
ucs2 = '61006200'
print(type(ucs2))
d = binascii.unhexlify(ucs2)

#utf로 전환
print(len(d), d)
print(d.decode("utf-8"))

<class 'str'>
4 b'a\x00b\x00'
ab


In [687]:
!ls

BeautifulSoup_test_20170120.ipynb
GitHub
My Music
My Pictures
My Videos
Processing
__pycache__
add_a_workbook.xlsx
arraystore.nd
arraystore.npy
arraystore.txt
bdsc4j.csv.xlsx
bs4_google_20170130.ipynb
country_data.xml
data.bin
data.txt
data.txt1
data1.bin
data1.txt
date_time_test_20170130.ipynb
decoraotor_test_20161030.ipynb
desktop.ini
dic_file.csv
dic_file1.csv
doc1.xml
ezPDFReader2.0
f
f.txt
f2.txt
fil.txt
file_test2_20170130.ipynb
file_test_20170130.ipynb
file_txt
file_txt1
fr.bin
fr.hex
fw
fw.bin
homemade.xml
import_worker
import_worker.py
index.html
json_myobj.py
lxml_test.xml
matplotlib_test_20161110.ipynb
mp_sample.py
mp_sample1.py
multi_test.py
myfile.html
note.xml
numpy_20161110.ipynb
numpy_test_20161115.ipynb
page.xhtml
pandas test_20161110.ipynb
persons.csv
persons1.csv
plugin-descriptor.properties
pool_map.py
pool_map1.py
printfile.bin
printfile.txt
process_apply.py
process_applyasync.py
process_daemon.py
process_daemon1.py
process_main.py
process_mapasync.py
process_npsqr

In [689]:
contents = !ls
print(contents[:2])

['BeautifulSoup_test_20170120.ipynb', 'GitHub']


In [695]:
contents = !ls
print(contents[:2])

!cd
path = !cd
print(path)

!echo "printing from the shell"
message = "hello from Python"
!echo {message}


['BeautifulSoup_test_20170120.ipynb', 'GitHub']
C:\Users\06411\Documents
['C:\\Users\\06411\\Documents']
"printing from the shell"
hello from Python


In [698]:
%magic

In [702]:
%mkdir test_dir
lsl = %ls
%cd test_dir

 C 드라이브의 볼륨: SYSTEM
 볼륨 일련 번호: 4A5F-4E72

 C:\Users\06411\Documents\test_dir 디렉터리

2017-01-05  오전 11:59    <DIR>          .
2017-01-05  오전 11:59    <DIR>          ..
2017-01-05  오전 11:59    <DIR>          test_dir
               0개 파일                   0 바이트
               3개 디렉터리  37,983,842,304 바이트 남음
C:\Users\06411\Documents\test_dir\test_dir


In [724]:
!env

!C:=C:\Users\06411\Documents
CLICOLOR=1
GIT_PAGER=cat
JPY_INTERRUPT_EVENT=968
MPLBACKEND=module://ipykernel.pylab.backend_inline
NUMBER_OF_PROCESSORS=4
JPY_PARENT_PID=964
ALLUSERSPROFILE=C:\ProgramData
PAGER=cat
PROCESSOR_ARCHITEW6432=AMD64
PROMPT=$P$G
TERM=xterm-color
USERDOMAIN=SKCC
PUBLIC=C:\Users\Public
MYSQL_HOME=C:\mysql-5.6.22-winx64
SYSTEMROOT=C:\Windows
PSMODULEPATH=C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
TEMP=/tmp
LOGONSERVER=\\SKCC-HSKPDC2
PROGRAMFILES(X86)=C:\Program Files (x86)
WINDOWS_TRACING_LOGFILE=C:\BVTBin\Tests\installpackage\csilogfile.log
USERNAME=06411
DOCKER_TOOLBOX_INSTALL_PATH=C:\Program Files\Docker Toolbox
COMSPEC=C:\Windows\system32\cmd.exe
GOPATH=c:\workspace
HOMEDRIVE=C:
PATH=/c/Program Files/Anaconda3/Library/bin:/c/Program Files/Anaconda3/Library/bin:/c/Program Files/Anaconda3:/c/Program Files/Anaconda3/Scripts:/c/Program Files/Anaconda3/Library/bin:/c/Program Files/Anaconda3/Library/bin:/c/Python27/Lib/site-packages/PyQt4:/c/Program Files (x

In [713]:
%cd C:\Users\06411\Documents


C:\Users\06411\Documents


In [714]:
%rmdir .\test_dir\test_dir
%cd C:\Users\06411\Documents

C:\Users\06411


In [715]:
%cd C:\Users\06411\Documents

C:\Users\06411\Documents


In [717]:
%pwd

'C:\\Users\\06411\\Documents'

In [718]:
%mv?

Object `%mv` not found.


In [722]:
%echo "test"

"test"


In [728]:
a = int(1)

print(a)
print(type(a))
print(isinstance(a, int))

1
<class 'int'>
True


In [734]:
lt = [1,'s',['b','c']]
print(id(lt), type(lt))
print(id(lt[0]), type(lt[0]) )
print(id(lt[1]), type(lt[1]) )
print(id(lt[2]), type(lt[2]) )

81466440 <class 'list'>
1562313200 <class 'int'>
6119296 <class 'str'>
95722760 <class 'list'>


In [741]:
import numpy as np

nda = np.array([1,2,3,4,5])
print(nda.shape)
print(nda.dtype)
print(nda.ndim)
print(nda.strides)
print(nda.data.tolist())


(5,)
int32
1
(4,)
[1, 2, 3, 4, 5]


In [747]:
import array
L = list(range(10))
A = array.array('i', L)
print(A)
print(A.typecode)
print(A.tolist())
print(A.buffer_info())

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
i
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
(69207456, 10)


In [750]:
import numpy as np

# integer array:
i = np.array([1, 4, 2, 5, 3])
print(i)
print(i.dtype)

# float array:
f = np.array([3.14, 4, 2, 3])
print(f)
print(f.dtype)

# nested lists result in multi-dimensional arrays
mi = np.array([range(i, i + 3) for i in [2, 4, 6]])
print(mi)

[1 4 2 5 3]
int32
[ 3.14  4.    2.    3.  ]
float64
[[2 3 4]
 [4 5 6]
 [6 7 8]]


In [751]:
# Create a length-10 integer array filled with zeros
ze = np.zeros(10, dtype=int)
print(ze)
# Create a 3x5 floating-point array filled with ones
one = np.ones((3, 5), dtype=float)
print(one)
# Create a 3x5 array filled with 3.14
fl = np.full((3, 5), 3.14)
print(fl)

[0 0 0 0 0 0 0 0 0 0]
[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
[[ 3.14  3.14  3.14  3.14  3.14]
 [ 3.14  3.14  3.14  3.14  3.14]
 [ 3.14  3.14  3.14  3.14  3.14]]


In [752]:
import numpy as np

# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
ar = np.arange(0, 20, 2)
print(ar)

# Create an array of five values evenly spaced between 0 and 1
ls = np.linspace(0, 1, 5)
print(ls)

[ 0  2  4  6  8 10 12 14 16 18]
[ 0.    0.25  0.5   0.75  1.  ]


In [753]:
import numpy as np

# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
rr = np.random.random((3, 3))
print(rr)

# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
rn = np.random.normal(0, 1, (3, 3))
print(rn)

# Create a 3x3 array of random integers in the interval [0, 10)
ri = np.random.randint(0, 10, (3, 3))
print(ri)

[[ 0.88050071  0.79042114  0.81195593]
 [ 0.10219646  0.477742    0.71939974]
 [ 0.29968495  0.31610957  0.42161167]]
[[ 0.27567609 -0.00974696  0.35981263]
 [ 1.55050238  0.26103931 -0.06907681]
 [-0.24800385 -1.48016813 -0.45919365]]
[[3 2 4]
 [8 1 1]
 [7 2 6]]


In [754]:
import numpy as np

# Create a 3x3 identity matrix
ey = np.eye(3)
print(ey)

# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
em = np.empty(3)
print(em)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[ 1.  1.  1.]


In [755]:
import numpy as np

z1 =np.zeros(10, dtype='int16')
print(z1)
print(z1.dtype)

z2 =np.zeros(10, dtype=np.int16)
print(z2)
print(z2.dtype)

[0 0 0 0 0 0 0 0 0 0]
int16
[0 0 0 0 0 0 0 0 0 0]
int16


In [763]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array
print(x3.flatten())
print("x3 차원   : ", x3.ndim)
print("x3 형태   :", x3.shape)
print("x3 size:  :", x3.size)
print("x3 dtype  :", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

[5 0 3 3 7 9 3 5 2 4 7 6 8 8 1 6 7 7 8 1 5 9 8 9 4 3 0 3 5 0 2 3 8 1 3 3 3
 7 0 1 9 9 0 4 7 3 2 7 2 0 0 4 5 5 6 8 4 1 4 9]
x3 차원   :  3
x3 형태   : (3, 4, 5)
x3 size:  : 60
x3 dtype  : int32
itemsize: 4 bytes
nbytes: 240 bytes


In [761]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array

print(x1.flatten())
print("x1 차원   : ", x1.ndim)
print("x1 형태   :", x1.shape)
print("x1 size:  :", x1.size)
print("x1 dtype  :", x1.dtype)
print("itemsize:", x1.itemsize, "bytes")
print("nbytes:", x1.nbytes, "bytes")

[5 0 3 3 7 9]
x1 차원   :  1
x1 형태   : (6,)
x1 size:  : 6
x1 dtype  : int32
itemsize: 4 bytes
nbytes: 24 bytes


In [762]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array

print(x2.flatten())
print("x2 차원   : ", x2.ndim)
print("x2 형태   :", x2.shape)
print("x2 size:  :", x2.size)
print("x2 dtype  :", x2.dtype)
print("itemsize:", x2.itemsize, "bytes")
print("nbytes:", x2.nbytes, "bytes")

[5 0 3 3 7 9 3 5 2 4 7 6]
x2 차원   :  2
x2 형태   : (3, 4)
x2 size:  : 12
x2 dtype  : int32
itemsize: 4 bytes
nbytes: 48 bytes


In [767]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(6, size=6)  # One-dimensional array
x2 = np.random.randint(8, size=(3, 2))  # Two-dimensional array
x3 = np.random.randint(12, size=(3, 2, 2))  # Three-dimensional array

print(x1[0])
print(x2[0])
print(x3[0])

print(x1[-1])
print(x2[-1])
print(x3[-1])

4
[7 1]
[[7 6]
 [8 8]]
3
[2 4]
[[7 8]
 [1 5]]


In [771]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(6, size=6)  # One-dimensional array
x2 = np.random.randint(8, size=(3, 2))  # Two-dimensional array
x3 = np.random.randint(12, size=(3, 2, 2))  # Three-dimensional array

print(x1[:2])
print(x2[:2])
print(x3[:2])

print(x1[-1:])
print(x2[-1:])
print(x3[-1:])

[4 5]
[[7 1]
 [3 5]]
[[[ 7  6]
  [ 8  8]]

 [[10  1]
  [ 6  7]]]
[3]
[[2 4]]
[[[7 8]
  [1 5]]]


In [778]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x2 = np.random.randint(8, size=(3, 2))  # Two-dimensional array

print(x2)
print(x2[1, 1]) # 두번째 행, 두번째 열 원소 검색
print(x2[1, :]) # 두번째 행
print(x2[::-1, ::-1]) # 역으로 출력


[[4 7]
 [5 0]
 [3 3]]
0
[5 0]
[[3 3]
 [0 5]
 [7 4]]


In [780]:
import numpy as np

x2 = np.random.randint(8, size=(3, 2))  # Two-dimensional array
print(x2)
print(" slice 배열 조회")
x2_sub = x2[:2, :2]
print(x2_sub)
print(" slice 배열 변경")
x2_sub[0, 0] = 99
print(x2_sub)
print("원본 배열 ")
print(x2)

[[4 7]
 [6 0]
 [0 4]]
 slice 배열 조회
[[4 7]
 [6 0]]
 slice 배열 변경
[[99  7]
 [ 6  0]]
원본 배열 
[[99  7]
 [ 6  0]
 [ 0  4]]


In [782]:
import numpy as np

x2 = np.random.randint(8, size=(3, 2))  # Two-dimensional array
print(x2)
print(" slice 배열 조회 및 복사 ")
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)
print(" slice 배열 변경")
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)
print("원본 배열 ")
print(x2)

[[0 1]
 [5 1]
 [5 0]]
 slice 배열 조회 및 복사 
[[0 1]
 [5 1]]
 slice 배열 변경
[[42  1]
 [ 5  1]]
원본 배열 
[[0 1]
 [5 1]
 [5 0]]


In [785]:
import numpy as np

#reshape 메소드 처리
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

#reshape 함수 처리

x = np.array([1, 2, 3,4,5,6])
xx = np.reshape(x,(2, 3))
print(xx)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]


In [791]:
import numpy as np

#reshape 메소드 처리
x = np.arange(0, 3)
# row vector via newaxis
rx = x[np.newaxis, :]
print(rx)

# column vector via reshape
xs = x.reshape((3, 1))
print(xs)
xc = x[ :, np.newaxis]
print(xc)

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0]
 [1]
 [2]]


In [793]:
import numpy as np

grid = np.array([[1, 2, 3],[4, 5, 6]])

# concatenate along the first axis
ax0 = np.concatenate([grid, grid], axis=0)
print(ax0)

# concatenate along the second axis (zero-indexed)
ax1 = np.concatenate([grid, grid], axis=1)
print(ax1)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [794]:
import numpy as np
grid = np.array([[1, 2, 3],[4, 5, 6]])

# vertically stack the arrays
av = np.vstack([grid, grid])
print(av)

# horizontally stack the arrays

ah =np.hstack([grid, grid])
print(ah)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [818]:
import numpy as np

x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3,5])
print(x1, x2, x3)
x = [[1, 2, 3, 99,100, 88,99], [99, 3, 2, 1,100,88,99]]
x1, x2, x3, x4  = np.split(x, [2,5,7], axis=1)
print(x1)
print(x2)
print(x3)
print(x4)


[1 2 3] [99 99] [3 2 1]
[[ 1  2]
 [99  3]]
[[  3  99 100]
 [  2   1 100]]
[[88 99]
 [88 99]]
[]


In [807]:
import numpy as np

x = [1, 2, 3, 99, 99, 3, 2, 1]

xa = np.array(x).reshape(4,2)
upper, lower = np.vsplit(xa, [2])
print(upper)
print(lower)

left, right = np.hsplit(xa , [1])
print(left)
print(right)

[[ 1  2]
 [ 3 99]]
[[99  3]
 [ 2  1]]
[[ 1]
 [ 3]
 [99]
 [ 2]]
[[ 2]
 [99]
 [ 3]
 [ 1]]


In [819]:
import numpy as np

x = [1, 2, 3, 99, 99, 3, 2, 1]
x

In [820]:
def add(x:int, y:int) ->int :
    return x+y

add

In [821]:
class Person(object) :
    def __init__(self, name) :
        self.name = name
        
    def getName(self) :
        return self.name
    

In [826]:
import unicodedata

u = chr(233) + chr(0x0bf2) + chr(3972) + chr(6000) + chr(13231)

for i, c in enumerate(u):
    # hex값 표시
    print(i, '%04x' % ord(c), end=" ")
    #문자 범주 표시
    print(unicodedata.category(c), end=" ")
    # 문자 표시
    print(unicodedata.lookup(unicodedata.name(c)), end=" ")
    # 문자의 이름
    print(unicodedata.name(c))

0 00e9 Ll é LATIN SMALL LETTER E WITH ACUTE
1 0bf2 No ௲ TAMIL NUMBER ONE THOUSAND
2 0f84 Mn ྄ TIBETAN MARK HALANTA
3 1770 Lo ᝰ TAGBANWA LETTER SA
4 33af So ㎯ SQUARE RAD OVER S SQUARED


In [834]:
import re
p = re.compile('\d+')

s = "Over \u0e55\u0e57 57 flavours"
print(unicodedata.name('\u0e55'))
print(unicodedata.name('\u0e57'))
m = p.search(s)
print(repr(m.group()))

THAI DIGIT FIVE
THAI DIGIT SEVEN
'๕๗'


In [835]:
import re
p = re.compile('\d+', re.ASCII)

s = "Over \u0e55\u0e57 57 flavours"

m = p.search(s)
print(repr(m.group()))

THAI DIGIT FIVE
THAI DIGIT SEVEN
'57'


In [838]:
from string import Template

s = Template('$who likes $what')
print(s.substitute(who='tim', what='kung pao'))


tim likes kung pao


In [837]:
from string import Template
s = Template('$who likes $what')

d = dict(who='tim')
Template('$who likes $what').substitute(d)

KeyError: 'what'

In [840]:
from string import Template
s = Template('$who likes $what')

d = dict(who='tim')
print(Template('$who likes $what').safe_substitute(d))

tim likes $what


In [875]:
import string

print(string.ascii_letters)
print(string.ascii_lowercase)
print(string.ascii_uppercase)
print(string.digits)
print(string.hexdigits)
print(string.octdigits)
print(string.punctuation)
print(string.printable)
print("%r " % string.whitespace)

abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
abcdefghijklmnopqrstuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ
0123456789
0123456789abcdefABCDEF
01234567
!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~ 	

' \t\n\r\x0b\x0c' 


In [841]:
s = 'string'
print(id(s))

v = "updating " + s
print(id(v))
print(v)
print(s) 


10595328
131491376
updating string
string


In [843]:
s = "python"

print(max(s))
print(min(s))
print(len(s))

y
h
6


In [845]:
print(r"helle\n world")
print("helle\n world")

helle\n world
helle
 world


In [846]:
print(' start ')
for i in dir(bytes) :
    if i in dir(str) :
        pass
    else :
        print(i)
else :
    print(' end ')


 start 
decode
fromhex
hex
 end 


In [847]:
b = b'abc'
print(b)
print(b[0])
print(b[1])
print(b[2])
b[1] =100

b'abc'
97
98
99


TypeError: 'bytes' object does not support item assignment

In [848]:
print(' start bytearray')

for i in dir(bytearray) :
    if i in dir(str) :
        pass
    else :
        print(i)
else :
    print(' end ')


 start bytearray
__alloc__
__delitem__
__iadd__
__imul__
__setitem__
append
clear
copy
decode
extend
fromhex
hex
insert
pop
remove
reverse
 end 


In [853]:
ba = bytearray('abcdef', "utf-8")
print(ba)

print(type(ba))
print(ba[3])
print(ord('d'))

#integer로 변경해야 함
ba[2] = 110
print(ba)


bytearray(b'abcdef')
<class 'bytearray'>
100
100
bytearray(b'abndef')


In [858]:
s=bytearray('abcdef', "utf-8")
print(s)

print(ord('^'))
s.insert(0, 94)
print(s)

s.pop()
print(s)

t  =  bytearray(b'abcdef')
t.append(120)
print(t) 


bytearray(b'abcdef')
94
bytearray(b'^abcdef')
bytearray(b'^abcde')
bytearray(b'abcdefx')


In [860]:
c = bytearray('abcd', "utf-8")

print(c)

c[3] = ord('x')
print(c)

c[3] = 102    #ord(‘f’) = 102
print(c)


bytearray(b'abcd')
bytearray(b'abcx')
bytearray(b'abcf')


In [865]:
b = bytearray('abcedf',"utf-8")

print(b)
print(b[2:4])

#슬라이싱으로 갱신할 경우는
#byte,bytearray로 할당 가능
b[2:4] = b'#'
print(b)
print(len(b))


bytearray(b'abcedf')
bytearray(b'ce')
bytearray(b'ab#df')
5


In [868]:
d = bytearray('12345',"utf-8")
d.reverse()
print(d)

# bytearray에는 sort 메소드가 없음
d1 =bytearray(sorted(d))
print(d1)


bytearray(b'54321')
bytearray(b'12345')


In [870]:
sa = 'abc'
aa = sa.encode('ascii')
print(type(aa), aa)

aas = aa.decode('utf-8')
print(type(aas), aas)

aass = aas.encode('utf-8')
print(type(aass), aass)


<class 'bytes'> b'abc'
<class 'str'> abc
<class 'bytes'> b'abc'


In [883]:
s = str("helloworld")
print(s.capitalize())
print(s.title())
su = s.upper()
print(su)
print(su.lower())
print(s.title())
print("ABCdef".swapcase())

Helloworld
Helloworld
HELLOWORLD
helloworld
Helloworld
abcDEF


In [938]:
s = str("hello world")
ss = s.split(" ")
print(ss)
sj = " ".join(ss)
print(sj)

sr = s.rsplit(" ")
print(sr)

['hello', 'world']
hello world
['hello', 'world']


In [935]:
l = "ae,iou"

#분리자를 포함해서 분리
print(l.partition(","))
print(l.rpartition(","))

('ae', ',', 'iou')
('ae', ',', 'iou')


In [887]:
help(sx.splitlines)

Help on built-in function splitlines:

splitlines(...) method of builtins.str instance
    S.splitlines([keepends]) -> list of strings
    
    Return a list of the lines in S, breaking at line boundaries.
    Line breaks are not included in the resulting list unless keepends
    is given and true.



In [892]:
s = str("hello world")
print(s.find('o'))
print(s.rfind('o'))
print(s.index('o'))
print(s.rindex('o'))

4
7
4
7


In [893]:
s = str("hello world")
print(s.startswith("hello"))
print(s.endswith("world"))

True
True


In [898]:
s = str("hello world")
print(s.ljust(30,"#"))
print(s.rjust(30,"#"))
s = str("    hello world    ")
print(s.strip())
print(s.lstrip())
print(s.rstrip())

hello world###################
###################hello world
hello world
hello world    
    hello world


In [903]:
s = str("hello world")
print(s.center(30,"-"))
print(s.count('o'))

st = str("\thello world")
print(st.expandtabs(10))


---------hello world----------
2
          hello world


In [905]:
s = str("hello world")
print(s.encode("utf-8"))
print(s.encode('ascii'))

print(s.replace("llo", "xxx"))

b'hello world'
b'hello world'
hexxx world


In [907]:
intab = "aeiou"
outtab = "12345"
trantab = "".maketrans(intab, outtab)
print(trantab)

st = "this is string example....wow!!!"
print(st.translate(trantab))

{97: 49, 111: 52, 117: 53, 101: 50, 105: 51}
th3s 3s str3ng 2x1mpl2....w4w!!!


In [911]:
al = "aeiou"
print(al.isalpha())
nm = "12345"
print(nm.isnumeric())
alnm = "aeiou12345"
print(alnm.isalnum())

True
True
True


In [918]:
l = "aeiou"
print(l.islower())
u = "ABCED"
print(u.isupper())
t = "Abc Def"
print(t.istitle())
s ="   \n"
print(s.isspace())

True
True
True
True


In [920]:
l = "ae,iou"

#분리자를 포함해서 분리
print(l.partition(","))

('ae', ',', 'iou')


In [927]:
sx = str("hello\n world\n python\n")
s1 = sx.splitlines(ord('\n'))
print(s1)
srx = str("hello\r\n world\r\n python\r\n")
s2 = srx.splitlines(ord('\r')+ord('\n'))
print(s2)

['hello\n', ' world\n', ' python\n']
['hello\r\n', ' world\r\n', ' python\r\n']


In [924]:
help(str.splitlines)

Help on method_descriptor:

splitlines(...)
    S.splitlines([keepends]) -> list of strings
    
    Return a list of the lines in S, breaking at line boundaries.
    Line breaks are not included in the resulting list unless keepends
    is given and true.



In [933]:
import collections.abc as abc

#immutable type
print(issubclass(str,abc.Sequence))
print(issubclass(bytes,abc.Sequence))
print(issubclass(bytearray,abc.Sequence))

#mutable type
print(issubclass(str,abc.MutableSequence))
print(issubclass(bytes,abc.MutableSequence))
print(issubclass(bytearray,abc.MutableSequence))

True
True
True
False
False
True


In [939]:
print("42".zfill(5))

print("-42".zfill(5))

00042
-0042
